### ISSUE TITLE
Setup continuous integration with GitHub Actions 

### ISSUE THREAD

**Issue by NadHodeGW** [k8-proxy/aws-jmeter-test-engine#14]

**Comment by uzfarid** [comment]
@upworkroozbeh work needs to include clear instructions as well.

**Comment by uzfarid** [comment]
sometips

https://github.com/marketplace/actions/aws-cloudformation-deploy-cloudformation-stack-action-for-github-actions
https://aws.amazon.com/blogs/opensource/deploy-aws-cloudformation-stacks-with-github-actions/

**Comment by uzfarid** [comment]
this issue is about writing clear instructions on how a script can run using GitHub actions. example script is https://github.com/k8-proxy/aws-jmeter-test-engine-v1/blob/master/jmeter-icap-poc/cloudformation/create_stack.py in https://github.com/k8-proxy/aws-jmeter-test-engine-v1/tree/master/jmeter-icap-poc/cloudformation
