### ISSUE TITLE
Test Automatically generated AMI

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/aws-jmeter-test-engine#342]

**Comment by Ali-J2** [comment]
**packer-jmeter-scaled-ami-1612659481** Issues found:
1. The UI being used is not the scaled load UI, it is the OVA UI. Script ui_scaled.sh would just need to modify the cd directories to the right folder
2. changeIP will not update the IP addresses in the correct places because the IPs were updated before AMI creation. For example, the current hardcoded value in the AMI is "http://54.194.100.66:5000/" for the flask server. ChangeIP should probably not be run in AMI creation process.
3. Changes that need to be made to config.env: 
- GRAFANA_URL=localhost:3000 (note, ":3000" must be included)
- INFLUX_HOST=127.0.0.1
- USE_IAM_ROLE=yes (currently it is set to "no")
4. InfluxDB: When back end attempts to access database, we get: "ERROR: metrics.verify_database: database not found: proxysite". We need to create database "proxysite" in InfluxDB before deploying

**Comment by Ali-J2** [comment]
**packer-ova-demo-1612659580** Issues found:

Some of these are the same issues as above, will restate them for reference.

1. ChangeIP: After changing IPs, this will attempt to restart the flask_scaled.service, but in the case of OVA, we are using flask.service not flask_scaled.service.

2. Changes that need to be made to config.env: 
- GRAFANA_URL=localhost:3000 (note, ":3000" must be included)
- INFLUX_HOST=127.0.0.1

3. When attempting to run a test using the OVA UI, the following errors are produced:
"Failed to stop promtail.service: Unit promtail.service not loaded."
"Failed to start promtail.service: Unit promtail.service not found."
"An error occurred: The file /opt/jmeter/apache-jmeter-5.3/bin/ICAP_Direct_FileProcessing_Local_v4.jmx doesn't exist or can't be opened"

**Comment by uzfarid** [comment]
@Ali-J2 , for case 1. is it problem or not problem? in OVA we should not use scaled service. 

for case 3. then basically script path is wrong

**Comment by Ali-J2** [comment]
In case 1, changeIP will try to stop/start flask_scaled service, which does not exist in the OVA. This produces an error but also means that the flask service (which needs to be restarted after the change in values) is not restarted.

Case 3 has two issues, first one is that promtail needs to be installed in the image. Second issue is indeed because the script path is wrong in "LocalStartExecution.sh", that could be easily fixed (need to modify the "cd" command at line 10)

**Comment by Ali-J2** [comment]
@shashanksinha89 Regarding the following: "An error occurred: The file /opt/jmeter/apache-jmeter-5.3/bin/ICAP_Direct_FileProcessing_Local_v4.jmx doesn't exist or can't be opened", we need to add some files to the folder located at /opt/jmeter/apache-jmeter-5.3/bin. Those are:

1. ICAP_Direct_FileProcessing_Local_v4.jmx
2. ProxySite_Processing_v1.jmx
3. gov_uk_files.csv
4. proxysitefiles.csv

These can be found in the project's repo, in the scripts folder, under the two directories containing ICAP direct and proxy site files.

**Comment by shashanksinha89** [comment]
#406

**Comment by Ali-J2** [comment]
The current release's /opt/jmeter/apache-jmeter-5.3/bin/ folder looks like this:
![ova](https://user-images.githubusercontent.com/59252902/108234536-f0244600-7155-11eb-910e-c498cb1e4778.PNG)

**Comment by shashanksinha89** [comment]
#418

**Comment by shashanksinha89** [comment]
> @shashanksinha89 Regarding the following: "An error occurred: The file /opt/jmeter/apache-jmeter-5.3/bin/ICAP_Direct_FileProcessing_Local_v4.jmx doesn't exist or can't be opened", we need to add some files to the folder located at /opt/jmeter/apache-jmeter-5.3/bin. Those are:
> 
> 1. ICAP_Direct_FileProcessing_Local_v4.jmx
> 2. ProxySite_Processing_v1.jmx
> 3. gov_uk_files.csv
> 4. proxysitefiles.csv
> 
> These can be found in the project's repo, in the scripts folder, under the two directories containing ICAP direct and proxy site files.
> 
> above is for OVA

#418 addresses it.

**Comment by shashanksinha89** [comment]
> **packer-ova-demo-1612659580** Issues found:
>
> When attempting to run a test using the OVA UI, the following errors are produced:
>    "Failed to stop promtail.service: Unit promtail.service not loaded."
>    "Failed to start promtail.service: Unit promtail.service not found."

#419
